name: Samot Marketplace

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET : ${{ secrets.AWS_S3_BUCKET }}
      AWS_REGION: 'us-east-1'
      SOURCE_DIR : 'build'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v1

      # Setup Node.js build environment
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0


      # Install project dependencies
      - name: Install Dependencies
        run: yarn

      # Build the app
      - name: Build
        run: yarn build

      #Deploy to prod
      - name : Deploy Prod
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
        if: endsWith(github.ref, '/main')
        run: |
          npm install -g serverless@2.72.2
          cd nextjs && aws s3 sync s3://samot-nextjs-deployment/dev .serverless --delete
          serverless --env=dev
          aws s3 sync .serverless s3://samot-nextjs-deployment/dev --delete

          cd ../website && aws s3 sync s3://samot-nextjs-deployment/dev/website .serverless --delete
          serverless --env=dev
          aws s3 sync .serverless s3://samot-nextjs-deployment/dev/website --delete

          npm install serverless -g
          cd ../serverless && npm install && serverless deploy --stage dev